### ISSUE TITLE
How to add custom categories and remove Liquid syntax error

### ISSUE THREAD

**Issue by nikitavoloboev** [hugoferreira/papyrus-theme#1]
I want to first thank you for this beautiful theme, it is one of the few ones that has sepia background and I love it.

I am trying to port a blog I have to this site and I have cloned the repository and followed the instructions, I also changed the config.yaml file with the values I wanted and everything built well. However as soon as I tried changing on of the blog posts, I got an error like so : 

![2016-11-29 at 01 22](https://cloud.githubusercontent.com/assets/6391776/20691588/3f75a1fc-b5d2-11e6-8c75-ff529eeb7f99.png)

Or here it is in text : 

```Bash
jekyll build                                                                 
Configuration file: /Users/nikivi/oss/nikivi/blog/papyrus-theme/_config.yml
            Source: /Users/nikivi/oss/nikivi/blog/papyrus-theme
       Destination: /Users/nikivi/oss/nikivi/blog/papyrus-theme/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
    Liquid Warning: Liquid syntax error (line 51): Expected id but found pipe in "{{ category || first }}" in index.html
                    done in 0.048 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

I tried searching online for this problem and couldn't really find anything I could use to fix this. The post I have in the _posts is as follows : 

![2016-11-29 at 01 24](https://cloud.githubusercontent.com/assets/6391776/20691638/8b489e36-b5d2-11e6-95f0-531f5800f9ef.png)

Thank you for any help.

**Comment by hugoferreira** [comment]
Thank you for submitting the issue, Nikita, and I hope you enjoy the theme. @allejo 's commit fixed it in 06a3c19. Cheers.
